In [2]:
(lambda x, y:x*y)(2,3)

6

In [4]:
import re

In [6]:
email = "brejees_123@gmail.com"

In [12]:
re.split('_|\.|\@',email)

['brejees', '123', 'gmail', 'com']

In [16]:
age = int(input("what is your age?"))
print("otha! ",age" vayasana kabothi")

SyntaxError: invalid syntax (<ipython-input-16-aa47e3d3d79a>, line 2)

In [26]:
xx=list(map(lambda x,y:x*y,[1,2,3,4],[4,5,6,7]))

In [30]:
a=[1,2,3,4]
b=[6,7,8,9]

In [38]:
poda = list(filter(lambda x:x%2==0,a))
poda

[2, 4]

In [40]:
from functools import reduce

In [44]:
poda = reduce(lambda x, y: x*y, b)

In [93]:
x = 6*7*8*9
x

3024

# Class Task 1

In [99]:
"""1) Lambda creates a function
   2) Lambda function is faster than list comprehension 
   3) List comprehension creates a list
Reference : https://www.quora.com/Is-it-better-to-use-list-comprehensions-or-map-with-a-lambda-function-when-manipulating-elements-in-a-list
            https://www.codecademy.com/forum_questions/54675c4c52f863922e001fbf"""

'1) Lambda creates a function\n   2) Lambda function is faster than list comprehension \n   3) List comprehension creates a list\nReference : https://www.quora.com/Is-it-better-to-use-list-comprehensions-or-map-with-a-lambda-function-when-manipulating-elements-in-a-list\n            https://www.codecademy.com/forum_questions/54675c4c52f863922e001fbf'

# Class Task 2

In [66]:
numb = []
for i in range(1,20+1):
    numb.append(i)
numb
even_numbers = list(filter(lambda x:x%2==0,numb))
even_numbers

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]

# Class Task 3.1

In [75]:
import math
def sqrut(x):
    s = math.sqrt(x)
    return s

In [76]:
sqrut(4)

2.0

# Class Rask 3.2

In [97]:
import timeit
a = [4]
y = (list(map(lambda a: math.sqrt(a),a)))
y

[2.0]

In [98]:
""" 1) In function, the parameter can be fed later
    2) In Map, the paramet should be declared beforehand and also it applies operation on list or dictionary not on a single value"""

' 1) In function, the parameter can be fed later\n    2) In Map, the paramet should be declared beforehand and also it applies operation on list or dictionary not on a single value'

In [101]:
import numpy as np

In [125]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [126]:
np.shape(x)

(3,)

In [127]:
np.ndim(x)

1

In [128]:
type(x)

numpy.ndarray

In [130]:
y = np.array([[1,2,3],[4,5,6]])
print('y:\n',x)

y:
 [1 2 3]


In [132]:
np.shape(y)

(2, 3)

In [133]:
np.size(y)

6

In [134]:
np.ndim(y)

2

In [167]:
type(y)

numpy.ndarray

In [169]:
q = np.empty([3,3], dtype=int)
q

array([[-906348864,        652, 1309280778],
       [1936028783,  757935370, 1611279661],
       [1953525093,  539779193, 1768713845]])

In [177]:
np.zeros([3,3], dtype=int, order='c')

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [179]:
np.ones([3,4])

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Class Task II

In [182]:
emp = np.empty([1,3], dtype=int)
emp

array([[4128860, 6029375, 3801155]])

In [184]:
zer = np.zeros([1,3], dtype=int)
zer

array([[0, 0, 0]])

In [187]:
one = np.ones([1,3], dtype=int)
one

array([[1, 1, 1]])

In [190]:
answer = np.concatenate((emp,zer,one), axis=0 )
answer

array([[4128860, 6029375, 3801155],
       [      0,       0,       0],
       [      1,       1,       1]])

In [193]:
np.linspace(1,10,50, True)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])