# Class Task Poisson Distr. (Typing error)

In [ ]:
# 6 error per hour typing 77 words per minute
#Probability of 2 errors in 322 words?

In [240]:
60*77

4620

In [ ]:
# 6 error for 4620 words
# Probability of 2 error in 322 words?

In [241]:
(2/322)*4620

28.695652173913043

In [ ]:
# Now I can rephrase it as
# 6 error for 4620 words
# Probability of 28.6956 error for 4620 words?

In [243]:
import scipy.stats as stats

In [251]:
stats.poisson.pmf(28.696, 6)

0.0

# Class Task III

In [47]:
list(x[np.array([-6, -4, -2])])

[5, 7, 9]

In [51]:
x[x>4]

array([ 5,  6,  7,  8,  9, 10])

In [76]:
y = np.linspace(1,10,15)
y

array([ 1.        ,  1.64285714,  2.28571429,  2.92857143,  3.57142857,
        4.21428571,  4.85714286,  5.5       ,  6.14285714,  6.78571429,
        7.42857143,  8.07142857,  8.71428571,  9.35714286, 10.        ])

# Class Task IV

In [91]:
y = np.array([1.5,3,5, 9.1], dtype=object)

In [92]:
y

array([1.5, 3, 5, 9.1], dtype=object)

In [95]:
[i for i in y if isinstance (i, int)]

[3, 5]

# Class Task V

In [146]:
x= np.random.randint(1,93,9)
x = x.reshape(3,3)
x

array([[83, 24, 39],
       [39, 14, 67],
       [23, 78, 48]])

In [147]:
x = x[[1,2,0,2],[2,0,0,1]]
x

array([67, 23, 83, 78])

In [149]:
x = x.reshape(2,2)
x

array([[67, 23],
       [83, 78]])

# Class Task VI (Diff. between Reshape & Resize)

In [159]:
"""Resize changes the shape of the array permanently
Reshape do not changes the shape permanently untill and unless it is assigned to the same variable"""

'Resize changes the shape of the array permanently\nReshape do not changes the shape permanently untill and unless it is assigned to the same variable'

# Class Task VII (Diff. between Ravel & Flatten)

In [182]:
"Flatten do not affect the original array but flatten affect the original array even after assigning to a new variable"

'Flatten do not affect the original array but flatten affect the original array even after assigning to a new variable'

# Class Task Titanic

In [213]:
import pandas as pd

In [217]:
data = pd.read_csv('train.csv')

In [219]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [228]:
x = np.array(data['Embarked'], dtype=str)
x

array(['S', 'C', 'S', 'S', 'S', 'Q', 'S', 'S', 'S', 'C', 'S', 'S', 'S',
       'S', 'S', 'S', 'Q', 'S', 'S', 'C', 'S', 'S', 'Q', 'S', 'S', 'S',
       'C', 'S', 'Q', 'S', 'C', 'C', 'Q', 'S', 'C', 'S', 'C', 'S', 'S',
       'C', 'S', 'S', 'C', 'C', 'Q', 'S', 'Q', 'Q', 'C', 'S', 'S', 'S',
       'C', 'S', 'C', 'S', 'S', 'C', 'S', 'S', 'C', 'nan', 'S', 'S', 'C',
       'C', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'C', 'C', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'S', 'S', 'S', 'Q', 'S', 'C', 'S', 'S', 'C', 'S', 'Q',
       'S', 'C', 'S', 'S', 'S', 'C', 'S', 'S', 'C', 'Q', 'S', 'C', 'S',
       'C', 'S', 'S', 'S', 'S', 'C', 'S', 'S', 'S', 'C', 'C', 'S', 'S',
       'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'C',
       'Q', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S', 'S',
       'S', 'S', 'Q', 'S', 'S', 'C', 'S', 'S', 'C', 'S', 'S', 

In [231]:
np.unique(x)

array(['C', 'Q', 'S', 'nan'], dtype='<U3')

In [234]:
y = np.array(data['Sex'], dtype=str)
np.unique(y)

array(['female', 'male'], dtype='<U6')

In [235]:
z = np.array(data['Pclass'], dtype=str)
np.unique(z)

array(['1', '2', '3'], dtype='<U21')